### ISSUE TITLE
Missing spacing on the frontend

### ISSUE THREAD

**Issue by gyurmey2** [ndiego/nautilus#1]
Hi,
Nice theme, but I noticed a spacing issue.

Editor:

![editor](https://user-images.githubusercontent.com/113413673/189822327-98a9c009-f4ae-4704-8f91-3aae3f840722.jpg)

Frontend:

![frontend](https://user-images.githubusercontent.com/113413673/189822292-738b11b0-9645-4a7a-97b6-4e949b3cc970.jpg)

**Comment by ndiego** [comment]
The theme has changed substantially since 2022, so I am going to close this out. Feel free to reopen if the issue persists in the latest version.
